### ISSUE TITLE
Handle extra inputs for ticket opening flow

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppServicesSupportCenterPortal#106]
When the new FrameBlade change is live in the portal, there will be additional parameters that are passed in as part of the StartupInfo

Here are the additional parameters:
- featureUri: uri of the feature that we would like to open
- source: this is how we will know it is coming from ticket opening blade
- supportTopicId: support topic selected, we should log this
- workflowId: this is for joining data with the telemetry from the ticket opening process

**Comment by ShekharGupta1988** [comment]
with PR https://github.com/ShekharGupta1988/AppServicesSupportCenterPortal/pull/121 , We are now populating workflowId in all our events.  Once the open ticket blade changes are deployed, I'll verify this.

**Comment by ShekharGupta1988** [comment]
Done and deployed
