### ISSUE TITLE
Add Detector View

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppServicesSupportCenterPortal#114]
Just like Applens, in support center, we need to add:
1. List of all detectors with correlated/non-correlated but interesting markers
2. Detector View

Also, few detectors will have different view (much richer view), and by default a detector can have a predefined view for top level graph(for availability/perf) followed by detector graph.

**Comment by stevenernst131** [comment]
I have created a new event #115 for the list of detectors, in case we want to enable detector view for some from observations, but not expose the list yet.
