### ISSUE TITLE
SCIFrameBlade Event not present when support center is opened from Case Submission

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppServicesSupportCenterPortal#182]
SCIFrameBlade Event is not present when the blade is opened from case submission.

cluster('appsvcux').database('APPSvcUX').ClientTelemetry | where TIMESTAMP >= ago(6h) and source =~ "SupportCenter"
| parse ['data'] with * "ticketBladeWorkflowId=" ticketWorkflowId  ';' *
| where ticketWorkflowId != ''
| parse ['data'] with * "sessionId=" localSessionId  ';' *
| summarize count() by  action, localSessionId
| summarize count() by action 

action	count_
StartUp	22
AnalysisInitialized	19
CurrentAppHealth	21
AppAnalysisSummary	18
DowntimeVisitedSummary	8
Click	4
DetectorViewOpened	1
Message	4

**Comment by stevenernst131** [comment]
The event is showing up but was previously missing the workflow id, I have added it so now it should show up with all the other events
