### ISSUE TITLE
Add additional feedback option

### ISSUE THREAD

**Issue by stevenernst131** [ShekharGupta1988/AppServicesSupportCenterPortal#195]
Something like "Did this help?" and then ask for extra feedback

**Comment by ShekharGupta1988** [comment]
We can capture this data in kusto or are you thinking of something else?

**Comment by stevenernst131** [comment]
I was just thinking log an event just like we do with all the other actions. Doesn't need to be anything fancy

**Comment by ShekharGupta1988** [comment]
@stevenernst131  - this can be closed?
