### ISSUE TITLE
Linux: container start failure

### ISSUE THREAD

**Issue by michimune** [ShekharGupta1988/AppServicesSupportCenterPortal#230]

**Comment by ShekharGupta1988** [comment]
hi @michimune  - did you want to open this for Applens ? This repository is customer facing diagnose and solve experience. 
For app lens issues - https://github.com/ShekharGupta1988/AppLensV2

**Comment by ShekharGupta1988** [comment]
closing this one. Open a corresponding issue in applens repo.
