### ISSUE TITLE
Need to pass scm hostname for some solutions from the API

### ISSUE THREAD

**Issue by ShekharGupta1988** [ShekharGupta1988/AppServicesSupportCenterPortal#24]
For following solutions, we need the SCM hostname from the API:

- Kill w3wp process
- Open Kudu console (for web.config)

for now, we are using site name and default dns in the portal code but that will not work for scenarios like national clouds, few ILB ASE scenarios etc.

**Comment by ShekharGupta1988** [comment]
Not needed immediately.
A temporary change that I have done right now is
 let scmHostName = `https://${siteName.value}.scm.azurewebsites.net`;

But this can fail in few scenarios as described in the bug.

**Comment by stevenernst131** [comment]
I have solved this by getting site objects for all sites in app service plan and they have the scm hostname as part of that object
