### ISSUE TITLE
What is the lag time for ASC to discern issues? Is it 1-5 mins lag?

### ISSUE THREAD

**Issue by gaurap** [ShekharGupta1988/AppServicesSupportCenterPortal#57]
I was not able to see realtime 502. After 5 mins it did successfully detected app issue. Would it help to mention it somewhere?

**Comment by MattTatoczenko** [comment]
I am seeing this as well. Is it due to how it pulls the backend logs? I'm noticing that even though my app returns 500 errors, I'm getting a message saying it's healthy for the time being.

**Comment by stevenernst131** [comment]
The kusto data is 10-15 minutes delayed. We try to use pulse in order to see if it is currently healthy, but if pulse returns no data (if there is no traffic in the last 2 minutes) then it would default to the last kusto data.

Pulse is about 30-60 seconds delayed

**Comment by stevenernst131** [comment]
Please refer to #69 as this will handle empty observations, and we will display a message explaining that it is down now.
