### ISSUE TITLE
The recommendations aren't helpful for my application that constantly reports errors

### ISSUE THREAD

**Issue by madihahussain** [ShekharGupta1988/AppServicesSupportCenterPortal#69]
My app consistently throws a 500 error due to an exception and  the current solutions aren't helpful : 
restart app
scale up 
Enable and check Application Insights log 

![image](https://cloud.githubusercontent.com/assets/6403741/25449809/969c120c-2a82-11e7-8fd2-a46b5e34bc7c.png)

In this case,  I would suggest adding a solution to check if there were any recent deployments that caused the consistent failures 

Also, it would be helpful to provide info on the exception that we are seeing.

**Comment by madihahussain** [comment]
These recommendations would be helpful for my case : 
![image](https://cloud.githubusercontent.com/assets/6403741/25450355/49e5ac28-2a84-11e7-9043-6695f3cafa79.png)

**Comment by madihahussain** [comment]
I am not getting consistent response for this site. When I reproduced the issue again, it clearly told me that I have DivideByZero exception, when I had tried earlier, I didn't see that option. 

![image](https://cloud.githubusercontent.com/assets/6403741/25451503/f7635a78-2a87-11e7-9d8b-11c66651f62e.png)

**Comment by PraveenTB** [comment]
the Kusto delay is 10-15 mins - once the delay is over, you will start seeing more details on exceptions etc.
