### ISSUE TITLE
Recommedations for slow sites can be tweaked 

### ISSUE THREAD

**Issue by madihahussain** [ShekharGupta1988/AppServicesSupportCenterPortal#75]
All the requests for my site are super slow and they timeout on the server side , in this case , when I look at Support Center, it recognizes server error. It would be helpful if we can correlate the slowness/timeouts with the server errors .

![image](https://cloud.githubusercontent.com/assets/6403741/25450913/123d27c2-2a86-11e7-8890-d93840f59ceb.png)

**Comment by stevenernst131** [comment]
Out of scope for first cut. However we will be adding the graph oh latency #81
